#:schema packages/ardos-packer/ardos-packer-schema.json

version = "0.0.1-dev"

[hooks]
post-processing = "scripts/post-process-sysroot.sh"

[initrd]
build_script = "scripts/build-initramfs.sh"
[kernel]
url = "https://git.kernel.org/torvalds/t/linux-6.18-rc3.tar.gz"

[kernel.options]
FRAMEBUFFER_CONSOLE="n"
FRAMEBUFFER_CONSOLE_DEFERRED_TAKEOVER="n"
FRAMEBUFFER_CONSOLE_DETECT_PRIMARY="n"
FRAMEBUFFER_CONSOLE_ROTATION="n"
DRM_PANIC="y"
DRM_RADEON="y"
DRM_AMDGPU="y"
DRM_NOUVEAU="y"
DRM_I915="y"
DRM_VGEM="y"
DRM_VKMS="y"
DRM_VMWGFX="y"
DRM_GMA500="y"
DRM_UDL="y"
DRM_AST="y"
DRM_MGAG200="y"
DRM_QXL="y"
DRM_VIRTIO_GPU="y"
DRM_VIRTIO_GPU_KMS="y"
DRM_PANEL="y"
BTRFS_FS="y"
SQUASHFS="y"
SQUASHFS_ZSTD="y"
SQUASHFS_COMPILE_DECOMP_SINGLE="n"
SQUASHFS_COMPILE_DECOMP_MULTI_PERCPU="y"

[[package]]
name = "glibc-ardos"
version = "2.41"
[package.source]
mode = "pkgbuildlocal"
path = "packages/glibc"


[[package]]
name = "llvm-mesa"
version = "22.1.1"
[package.source]
mode = "pkgbuildlocal"
path = "packages/llvm-mesa" 

[[package]]
name = "libgcc"
version = "15.2.1+r604+g0b99615a8aef"
[package.source]
mode = "binary"
url = "https://mirror.moson.org/arch/core/os/x86_64/libgcc-15.2.1+r604+g0b99615a8aef-1-x86_64.pkg.tar.zst"
sha256 = "00EBC06EF4B8FF5C1FD7BD7B6FAAFDC7C3BFA7F1F3A170FF2F2025D1F0B62ACE"
[[package]]
name = "libstdc++"
version = "15.2.1+r604+g0b99615a8aef"
[package.source]
mode = "binary"
url = "https://mirror.moson.org/arch/core/os/x86_64/libstdc++-15.2.1+r604+g0b99615a8aef-1-x86_64.pkg.tar.zst"
sha256 = "73DC1B0000E915339759D9492BB30E93FF343E041D5D5601B2BEFDA12235EC78"

[[package]]
name = "mesa"
version = "26.0.2"
build_deps = ["llvm-mesa"]
[package.source]
mode = "pkgbuildlocal"
path = "packages/mesa"
pick_packages_from_group = [
  "mesa",
  "vulkan-broadcom",
  "vulkan-dzn",
  "vulkan-intel",
  "vulkan-nouveau",
  "vulkan-radeon",
  "vulkan-virtio",
  "vulkan-mesa-implicit-layers",
  "vulkan-mesa-layers"
]
[package.docker]
dockerfile_path = "packages/mesa/Dockerfile"

[[package]]
name = "spirv-tools"
version ="1.4.341.0"

[package.source]
mode ="binary"
url = "https://mirror.moson.org/arch/extra/os/x86_64/spirv-tools-1:1.4.341.0-2-x86_64.pkg.tar.zst"
sha256 = "4B1C76864DA8E14B7ED034FA77F6CACAE2F3D959AADC980E1F284C7E75387C2C"
[[package]]
name = "spirv-llvm-translator"
version ="22.1.0"
build_deps = ["llvm-mesa", "spirv-tools"]
[package.source]
mode = "pkgbuildlocal"
path = "packages/spirv-llvm"
[[package]]
name = "zlib"
version ="1.3.2"

[package.source]
mode = "binary"
url ="https://umea.mirror.pkgbuild.com/core/os/x86_64/zlib-1:1.3.2-3-x86_64.pkg.tar.zst"
sha256 = "41CF0BB5DF14E18F7FB868A97DA3FEB7C4127FBA99BB332AD54B14322FAAC1B1"


[[package]]
name = "xz"
version ="5.8.2"
[package.source]
mode = "binary"
url ="https://umea.mirror.pkgbuild.com/core/os/x86_64/xz-5.8.2-1-x86_64.pkg.tar.zst"
sha256 = "23BCEA71064A929C76F95A324B68E6856A8880C6F70D525F4A83C391CA07B88A"

[[package]]
name = "lz4"
version ="1.10.0"
[package.source]
mode = "binary"
url = "https://umea.mirror.pkgbuild.com/core/os/x86_64/lz4-1:1.10.0-2-x86_64.pkg.tar.zst"
sha256 = "C6200C776440678FE8C26ADAE6C104194B425D9393A9E3FC09F934363F0C39A6"

[[package]]
name = "zstd"
version ="1.5.7"
[package.source]
mode = "binary"
url = "https://umea.mirror.pkgbuild.com/core/os/x86_64/zstd-1.5.7-3-x86_64.pkg.tar.zst"
sha256 = "D4CF0049137124C8A025EEDFAD267A3E8A02310C9EFB9D1AE4A61AA1D02789FC"

[[package]]
name = "expat"
version ="2.7.5"
[package.source]
mode = "binary"
url = "https://umea.mirror.pkgbuild.com/core/os/x86_64/expat-2.7.5-1-x86_64.pkg.tar.zst"
sha256 = "788A328B29848CE0616C322F2B2AF231CF6B85D0FBB7A95A21F71DC38732C415"

[[package]]
name = "libdisplay-info"
version ="0.3.0"
[package.source]
mode = "binary"
url = "https://umea.mirror.pkgbuild.com/extra/os/x86_64/libdisplay-info-0.3.0-1-x86_64.pkg.tar.zst"
sha256 = "07AB1479EC5E70AEA174E2D0E340BD9364B507ED74F2DF3BFD51B3C6F40E5787"



[[package]]
name = "libelf"
version = "0.193"
[package.source]
mode = "pkgbuildlocal"
path = "packages/libelf"


[[package]]
name = "libdrm"
version = "2.4.131"
[package.source]
mode = "pkgbuildlocal"
path = "packages/libdrm"

[[package]]
name = "libpciaccess"
version ="0.19"
[package.source]
mode = "binary"
url = "https://london.mirror.pkgbuild.com/extra/os/x86_64/libpciaccess-0.19-1-x86_64.pkg.tar.zst"
sha256 = "EF533895E7688DA61749BEE185103435DBE635D9773D092FB0516E132817E39F"

[[package]]
name = "lm_sensors"
version ="3.6.2"
[package.source]
mode = "binary"
url = "https://london.mirror.pkgbuild.com/extra/os/x86_64/lm_sensors-1:3.6.2-1-x86_64.pkg.tar.zst"
sha256 = "5363304255A506CF71E1ED4F0464166E5F2AAD6F0AE444FE08CAFD8C83BF11FF"