name: Build ROM

on:
  push:
  pull_request:

jobs:
  build:
    name: ROM (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            nix-system: x86_64-linux
            runner: blacksmith-32vcpu-ubuntu-2404
            max-jobs: 32
          - arch: aarch64
            nix-system: aarch64-linux
            runner: blacksmith-32vcpu-ubuntu-2404
            max-jobs: 16
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            extra-substituters = https://ardos-os.cachix.org
            extra-trusted-public-keys = ardos-os.cachix.org-1:ER39Zub8rFCCCdjZ7VUG+654TvPFkH8fvk2Iofzt74s=
            experimental-features = nix-command flakes

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: ardos-os
          authToken: '${{ secrets.CACHIX_TOKEN }}'

      - name: Build ROM
        run: nix build ".#packages.${{ matrix.nix-system }}.rom" --max-jobs ${{ matrix.max-jobs }} --show-trace --print-build-logs

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: ardos-rom-${{ matrix.arch }}
          path: result
          retention-days: 14
